version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example_user_password

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - wp_data1:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: example_user_password

volumes:
  db_data1:
  wp_data1:
